### ISSUE TITLE
Day 1

### ISSUE THREAD

**Issue by L6Pin** [L6Pin/Faults_Reporting_React#1]

**Comment by L6Pin** [comment]
- [x] Create login page #2
- [x] Create mobile login form #4
- [x] Create login form component #6
- [x] Create profile page #8
