### ISSUE TITLE
Day 3

### ISSUE THREAD

**Issue by L6Pin** [L6Pin/Faults_Reporting_React#15]

**Comment by L6Pin** [comment]
- [x] Add API and Redux #16 
- [x] Create login functionality #18
- [x] Create add problem functionality #20
