### ISSUE TITLE
Day 4

### ISSUE THREAD

**Issue by L6Pin** [L6Pin/Faults_Reporting_React#23]

**Comment by L6Pin** [comment]
- [x] Create edit page #24
- [x] List user problems #26
- [x] Connect issue to problem form #28
