### ISSUE TITLE
Day 6

### ISSUE THREAD

**Issue by L6Pin** [L6Pin/Faults_Reporting_React#35]

**Comment by L6Pin** [comment]
- [x] Create logout functionality #36
- [x] Add route protection #38
- [x] Add redux persist #40
- [x] Add loader #42
- [x] Add filter by person #44
- [x] Add greeting message #46
